### ISSUE TITLE
Installation error: 'Sound.Tidal.MIDI.Params' not found

### ISSUE THREAD

**Issue by AlexisCaffa** [tidalcycles/tidal-midi-volca#1]
```
Sound/Tidal/MIDI/VolcaParams.hs:5:8:
    Could not find module ‘Sound.Tidal.MIDI.Params’
    Perhaps you meant
      Sound.Tidal.MIDI.Stream (from tidal-midi-0.8@tidal_IREyd5Juweb6ONUXg5BYzJ)
      Sound.Tidal.MIDI.SynthParams (from tidal-midi-0.8@tidal_IREyd5Juweb6ONUXg5BYzJ)
      Sound.Tidal.Params (from tidal-0.8@tidal_18qbC6bNtmhLTGf0DmSSUa)
```

SO: Ubuntu 16.04

Suggestions?

**Comment by kindohm** [comment]
When do you get this error?

Without knowing for sure what your issue is....

tidal-midi depends on tidal 0.8. Can you make sure that you have tidal
0.8 (or any 0.8.x) installed? You can see what you have installed by
typing "cabal list tidal" from a terminal. 

It's also possible there is some bug with the Volca module... but let's
see what you have installed first.

-Mike


-- 
  Mike Hodnick
  mike@kindohm.com

**Comment by AlexisCaffa** [comment]
I got the error when "cabal install" is executed.
```
$ cabal list tidal
* tidal
    Synopsis: Pattern language for improvised music
    Default available version: 0.8.2
    Installed versions: 0.8, 0.8.2

```
timi-midi works fine..

**Comment by kindohm** [comment]
oh, sorry, I didn't realize that this issue was in the `tidal-midi-volca` project. I'm not even sure this is a valid project any more....  @lennart is this project/module still active or necessary?

There are working Volca implementations in the `tidal-midi` project already: https://github.com/tidalcycles/tidal-midi/tree/master/Sound/Tidal/MIDI. If you already have tidal-midi installed, you should be able to use the `keysController`, `bassController`, and `beatsController` (assuming you have a Volca Keys, Bass, or Beats).

**Comment by AlexisCaffa** [comment]
Ah! ok.. 
Thanks you!

**Comment by lennart** [comment]
@kindohm we should close this project and link people to latest version of tidal-midi

**Comment by lennart** [comment]
i added a note in the readme to link to tidal-midi, we should however delete the repository to avoid confusion. feel free to do so @kindohm
